#######################
# SITE SETTINGS
#######################
title: 'ZLA小站' # The name of your blog, used in titles and meta tags.
subTitle: 'ZL Asica的个人小战' # A short description that appears after the main title.
description: 'ZL Asica的个人小站，发布个人技术和生活内容。生活内容会与微信公众号(ZL Asica)同步更新。' # A longer description for SEO and meta tags.
keywords: 'markdown blog, blog, sakura, ZL Asica, ZL Asica, ZLA, 嫒希卡' # Comma-separated keywords for SEO purposes.
author:
  name: 'ZL Asica' # Your name, displayed as the author of the blog.
  link: 'https://www.zla.app' # Link to your personal website or blog.
# Language setting: Use ISO 639-1 code (e.g., 'en' for English, 'zh' for Chinese)
lang: 'zh'
# Your public root url, used for SEO and meta tags.
# !Do not include a ending slash
siteUrl: 'https://www.zla.pub'

# Path to your avatar image. Can be a relative path from /public or a full URL (e.g., https://).
avatar: '/images/avatar.jpg'
# Used as the default thumbnail for posts without thumbnails.
background: '/images/background.jpg'
# Slogan displayed on your homepage, under your avatar.
slogan: 人和代码，有一个能跑就行～
# Google Analytics tracking ID (e.g., 'G-XXXXXXXXXX').
googleAnalytics: G-659VZ9NH28

#######################
# POSTS SETTINGS
#######################
creativeCommons:
  type: CC BY-SA 4.0 Deed
  link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans

#######################
# HEADER SETTINGS
#######################

#######################
# SOCIAL MEDIA SETTINGS
#######################
# Add your social media usernames.
# Leave the field empty if you do not want to display a specific platform.
# The order of the social media icons is determined by the order below.
socialMedia:
  github_username: ZL-Asica # Your GitHub username. https://github.com/username
  linkedin_username: elara-liu # Your LinkedIn username. https://www.linkedin.com/in/username
  instagram_id: zl_asica # Your Instagram username.
  orcid_id: 0009-0008-7221-2324 # Your ORCID iD.
  telegram_username: zl_asica # Your Telegram username. https://t.me/username
  x_username: # Your X (Twitter) username.
  youtube_id: ZL-Asica # Your YouTube channel ID. https://www.youtube.com/@username
  zhihu_username: zl_asica # Your Zhihu username. https://www.zhihu.com/people/username
  bilibili_id: 29018759 # Your Bilibili ID. https://space.bilibili.com/username
  email: zl@zla.app # Your email address.
  rss: # Your RSS feed URL.

#######################
# PAGES (ABOUT, FRIENDS) SETTINGS
#######################
# Have thumbnails for the about and friends pages.
thumbnailAbout: false
thumbnailFriends: false

#######################
# DISQUS (COMMENTS) SETTINGS
#######################
# Your Disqus shortname (used for integrating Disqus comments).
# Find this in your Disqus account: yoursite.disqus.com (shortname is the part before .disqus.com).
disqusShortname: 'zla-pub'

#######################
# CUSTOM CODE BLOCKS
# ! WARNING: Only modify these if you understand the purpose of custom scripts.
#######################
# Add custom JavaScript code to be included inside the <head> section of your site. One script per line.
headerJavascript:
  - https://cdn.jsdelivr.net/gh/zl-asica/web-cdn/js/zlasica.js
# Add custom HTML code to be included inside the <footer> section of your site.
slotFooter: |
  <!-- Add your custom footer HTML here -->
